repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.9.7
    hooks:
      - id: ruff
        description: "Check code for style and lint issues"
        language: python 
        types_or: [ python, pyi ]
        args: [ --fix ]
      - id: ruff-format
        description: "Check code for style and lint issues"      
        types_or: [ python, pyi ]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.389
    hooks:
      - id: pyright
        description: "Check code for static typing errors"
