repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # the release, git tag, or commit you want to use
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        description: "Check code for style and lint issues"
        language: python 
        types_or: [ python, pyi ]
        args: [ --fix ]
      - id: ruff-format
        description: "Check code for style and lint issues"      
        types_or: [ python, pyi ]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.389
    hooks:
      - id: pyright
        description: "Check code for static typing errors"
