repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        description: "Apply ruff linting"
        language: python
        args: [--fix]
      - id: ruff-format
        description: "Apply ruff formatting"

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.389
    hooks:
      - id: pyright
        description: "Check code for static typing errors"